### ISSUE TITLE
feat: variable to use parallel kurento servers

### ISSUE THREAD

**Issue by mschwrdtnr** [ebbba-org/ansible-role-bigbluebutton#120]
According the [bbb documentation](https://docs.bigbluebutton.org/2.2/customize.html#run-three-parallel-kurento-media-servers) it's recommend to use multiple kurento media servers.

It would be nice to have a task which automatically use `enableMultipleKurentos` set by the var `bbb_enableMultipleKurentos`.

A simple and working task could be to use `apply-config.sh`:

```
- name: Configure three kurento instances
  copy:
    dest: "/etc/bigbluebutton/bbb-conf/apply-config.sh"
    mode: 0777
    content: |
      #!/bin/bash
      source /etc/bigbluebutton/bbb-conf/apply-lib.sh
      enableMultipleKurentos
  notify:
    - restart bigbluebutton
  when: bbb_enableMultipleKurentos
```

I will implement this if you let me know what do you think about and what the best place would be.
