### ISSUE TITLE
Enabling the firewall breaks DNS resolution in AWS EC2

### ISSUE THREAD

**Issue by andreasscherbaum** [ebbba-org/ansible-role-bigbluebutton#142]
I'm trying to install this Playbook on an EC2 instance. For this I have to disable the firewall (which is enabled by default), otherwise after installing and enabling the firewall the Playbook fails with this step (one of the first tasks with network access once the firewall is up):
```
- name: add bigbluebutton.org repo key
  become: true
  apt_key:
    url: "{{ bbb_apt_mirror }}/repo/bigbluebutton.asc"
    id: '{{ bbb_apt_key }}'
```

Connecting to the EC2 instance reveals that DNS resolution is no longer working, and I also can't connect to external websites anymore, even when using the IP instead of a hostname. This works before the Playbook is started (verified), and the security settings for the instance are wide open (no limitations inbound/outbound).
