### ISSUE TITLE
[BUG] - kurento IPs not updated on change

### ISSUE THREAD

**Issue by DerDanilo** [ebbba-org/ansible-role-bigbluebutton#180]
**Describe the bug**
When the playbook was already run and BBB deployed, changes of the 'kurento' config block doesn't seem to be deployed while running the role again. I've had to manually change those IPs via cli.

Ansible doesn't seem to register any changes. I made sure to reference the right vars.yml, double and triple checked.

**To Reproduce**
1. Deploy bbb server with role playbook (e.g. with wrong IPs for freeswitch config)
2. change 'kurento and freeswitch' related IPs in vars
3. Deploy role playbook again
4. check with 'bbb-conf --check' and find that IPs actually haven't changed/are still wrong.

**Expected behavior**
IPs to be updated/changed when running role playbook again.

**Your variables for this role - be sure to remove any sensitive information**

```
...
bbb_freeswitch_ip_address: "{{ ansible_default_ipv4.address }}"
bbb_freeswitch_external_ip: "stun:{{ (bbb_stun_servers | first).server }}"
...
bbb_webrtc_sfu_multikurento:
  balancing-strategy: MEDIA_TYPE
  kurento:
    - ip: "{{ ansible_default_ipv4.address }}"
      url: ws://127.0.0.1:8888/kurento
      mediaType: main
      ipClassMappings:
        local: ""
        private: ""
        public: ""
      options:
        failAfter: 5
        request_timeout: 30000
        response_timeout: 30000
    - ip: "{{ ansible_default_ipv4.address }}"
      url: ws://127.0.0.1:8889/kurento
      mediaType: audio
      ipClassMappings:
        local: ""
        private: ""
        public: ""
      options:
        failAfter: 5
        request_timeout: 30000
        response_timeout: 30000
    - ip: "{{ ansible_default_ipv4.address }}"
      url: ws://127.0.0.1:8890/kurento
      mediaType: content
      ipClassMappings:
        local: ""
        private: ""
        public: ""
      options:
        failAfter: 5
        request_timeout: 30000
        response_timeout: 30000
  freeswitch:
    sip_ip: "{{ ansible_default_ipv4.address }}"
    ip: "{{ ansible_default_ipv4.address }}"
    esl_password: "{{ bbb_freeswitch_socket_password }}"
  log:
    level: warn
    filename:
```

Please let me know if you can reproduce this issue.
