### ISSUE TITLE
[BUG] - roles stops at task certificate-selfsigned.yml even though it's not used

### ISSUE THREAD

**Issue by d3hof** [ebbba-org/ansible-role-bigbluebutton#208]
**Describe the bug**
Running a play with the roles results in an openssl_privatekey error

**Expected behavior**
play should run

**Screenshots**
ERROR! couldn't resolve module/action 'openssl_privatekey'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in 'xx/certificate-selfsigned.yml': line 50, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Generate an OpenSSL private key
  ^ here

**Desktop information if needed (please complete the following information):**
 - OS: kubunut 20.04

**Ansible version**
```
ansible [core 2.11.2] 
  config file = /home/xxxi/git/ansible/bigbluebutton/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx.local/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

---
```
- hosts: xxx
  remote_user: root
  roles:
    - role: ebbba.bigbluebutton
     bbb_hostname: xxx
#      bbb_state:
#      bbb_apt_mirror:
      bbb_letsencrypt_enable: "true"
      bbb_letsencrypt_email: "xxxx"
#      bbb_letsencrypt_api:
#      bbb_nginx_privacy:
#      bbb_nginx_listen_https:
#      bbb_nginx_root:
#      bbb_ssl_cert:
#      bbb_ssl_key:
#      bbb_own_cert:
#      bbb_own_key:
      bbb_default_welcome_message: "Test"
      bbb_default_welcome_message_footer: "Test"
#      bbb_default_presentation:
#      bbb_custom_presentation:
#      bbb_custom_presentation_name:
      bbb_web_logouturl: "xxx"
      bbb_allow_request_without_session:
      bbb_coturn_enable: "no"
      bbb_coturn_server: "no"
#      bbb_coturn_port:
#      bbb_coturn_port_tls:
      bbb_coturn_secret: "{{ xxx }}"
#      bbb_coturn_min_port:
#      bbb_coturn_max_port:
      bbb_turn_enable: "yes"
      bbb_stun_servers:
      bbb_ice_servers:
      bbb_turn_servers:
#      bbb_greenlight_enable:
#      bbb_greenlight_hosts:
#      bbb_greenlight_image:
      bbb_greenlight_secret: "xxx"
      bbb_greenlight_db_password: "xxx"
#      bbb_greenlight_default_registration:
      bbb_greenlight_users: { name: 'xx', email: 'xx', password: 'xx', type: 'admin' }
      bbb_allow_mail_notifications: "false"
#      bbb_disable_recordings:
#      bbb_api_demos_enable:
#      bbb_client_log_enable:
#      bbb_mute_on_start:
#      bbb_app_log_level:
#      bbb_meteor:
#      bbb_nodejs_version:
#      bbb_system_locale:
      bbb_secret: "xxx
      bbb_freeswitch_ipv6: yes
#      bbb_freeswitch_ip_address:
#      bbb_freeswitch_external_ip:
#      bbb_dialplan_quality:
      bbb_dialplan_energy_level: "40"
#      bbb_dialplan_comfort_noise:
      bbb_webhooks_enable: "yes"
#      bbb_check_for_running_meetings:
#      bbb_monitoring_all_in_one_enable:
#      bbb_monitoring_all_in_one_version:
#      bbb_monitoring_all_in_one_port:
#      bbb_monitoring_all_in_one_grafana:
#      bbb_monitoring_all_in_one_prometheus:
#      bbb_monitoring_recordings_from_disk:
#      bbb_monitoring_external:
#      bbb_monitoring_htpasswd_user:
#      bbb_monitoring_htpasswd:
#      bbb_monitoring_exporter_version:
#      bbb_monitoring_systemd_enable:
#      bbb_monitoring_systemd_directory:
#      bbb_monitoring_systemd_port:
#      bbb_monitoring_systemd_bind_ip:
#      bbb_dialin_enabled:
#      bbb_dialin_provider_proxy:
#      bbb_dialin_provider_username:
#      bbb_dialin_provider_password:
#      bbb_dialin_provider_extension:
#      bbb_dialin_default_number:
#      bbb_dialin_mask_caller:
#      bbb_dialin_default_play_and_get_digitsbbb_dialin_overwrite_footer:
#      bbb_dialin_footer:
#      bbb_guestpolicy:
#      bbb_ntp_cron:
#      bbb_ntp_cron_day:
#      bbb_ntp_cron_hour:
#      bbb_ntp_cron_minute:
#      bbb_cron_history:
#      bbb_cron_unrecorded_days:
#      bbb_cron_published_days:
#      bbb_cron_log_history:
#      bbb_html5_node_options:
#      bbb_freeswitch_socket_password:
#      bbb_html5_backend_processes:
#      bbb_html5_frontend_processes:
#      bbb_container_compat:
#      bbb_firewall_ufw:
#      bbb_ufw_allow_networks_custom:
#      bbb_ufw_reject_networks_custom:
#      bbb_ssh_port:
#      bbb_max_file_size_upload:
#      bbb_default_max_users:
#      bbb_default_meeting_duration:
#      bbb_max_num_pages:
#      bbb_max_conversion_time:
#      bbb_num_conversion_threads:
#      bbb_num_file_processor_threads:
#      bbb_freeswitch_muted_sound:
#     bbb_freeswitch_unmuted_sound:
#     bbb_breakout_rooms_enabled:
#     bbb_breakout_rooms_record:
#     bbb_breakout_rooms_privatechat_enabled:
#     bbb_docker_compose_version:
#     bbb_docker_passwd:
#     bbb_docker_user:
  vars_files:
    - ./pw.yml

```
