### ISSUE TITLE
Not installing coturn should result in not applying ufw rules 

### ISSUE THREAD

**Issue by d3hof** [ebbba-org/ansible-role-bigbluebutton#217]
**Is your feature request related to a problem? Please describe.**
Ufw rules are applied for the coturn setup even though coturn installation is disabled.

**Describe the solution you'd like**
If you choose not to install coturn should result in not applying the ufw rules for the ufw setup.

**Describe alternatives you've considered**
I could change the role, but i think it would make more people happy if it just wasn't applied.

**Additional context**
```

  - name: Setup coturn rules
    community.general.ufw: "{{ item }}"
    with_items: "{{ bbb_firewall_ufw['rules']['coturn'] }}"
    when:
      - "'rules' in bbb_firewall_ufw"
      - "'coturn' in bbb_firewall_ufw['rules']"
      - bbb_coturn_enable

```
there already seems to be a condition for that, but it doesn't seem to work. I am taking a look at it, but I am new to ansible so questions could be asked here ;)

**Comment by d3hof** [comment]
So setting 
`      - bbb_coturn_enable`
 to
`      - bbb_coturn_enable | bool` 
results in the right rules applied.

But one issue might be that that if once wrongly applied the rules are not reset, so resetting the rules might seal the deal.
Not sure if i have to do that before or after enabling the firewall. Because the reset seems not to disable the default deny rule.

**Comment by BrutalBirdie** [comment]
What ansible version are you using?

**Comment by BrutalBirdie** [comment]
I just tested this:

```yml
bbb_coturn_enable: false
```

```bash
root@meet:~# ufw status
Status: active

To                         Action      From
--                         ------      ----
OpenSSH                    ALLOW       Anywhere
22/tcp                     LIMIT       Anywhere
443                        ALLOW       Anywhere
80                         ALLOW       Anywhere
16384:32768/udp            ALLOW       Anywhere
22                         ALLOW       Anywhere
10050                      ALLOW       Anywhere
OpenSSH (v6)               ALLOW       Anywhere (v6)
22/tcp (v6)                LIMIT       Anywhere (v6)
443 (v6)                   ALLOW       Anywhere (v6)
80 (v6)                    ALLOW       Anywhere (v6)
16384:32768/udp (v6)       ALLOW       Anywhere (v6)
22 (v6)                    ALLOW       Anywhere (v6)
10050 (v6)                 ALLOW       Anywhere (v6)

Anywhere                   ALLOW OUT   172.17.0.0/16
Anywhere                   ALLOW OUT   127.0.0.0/23
Anywhere                   REJECT OUT  0.0.0.0/8
Anywhere                   REJECT OUT  10.0.0.0/8
Anywhere                   REJECT OUT  100.64.0.0/10
Anywhere                   REJECT OUT  169.0.0.0/16
Anywhere                   REJECT OUT  192.0.2.0/24
Anywhere                   REJECT OUT  192.88.99.0/24
Anywhere                   REJECT OUT  192.168.0.0/16
Anywhere                   REJECT OUT  198.18.0.0/15
Anywhere                   REJECT OUT  198.51.100.0/24
Anywhere                   REJECT OUT  203.0.113.0/24
Anywhere                   REJECT OUT  224.0.0.0/4
Anywhere                   REJECT OUT  240.0.0.0/4
```

None of the default ports are allowed for coturn.

```yaml
bbb_coturn_enable: true
bbb_coturn_port: 3478
bbb_coturn_port_tls: 3443
bbb_coturn_server: "{{ bbb_hostname }}"
bbb_coturn_min_port: 49152
bbb_coturn_max_port: 65535
```

So I can not replicate your issue.

**Comment by d3hof** [comment]
Yes I know, but the documentation says _yes_ as default, the logic consequence is to use _no_ as the variable value in the play. In the other roles there actually is a _| bool_ behind the condition. So either the documentation has to be changed or to be safe add the _| bool_ to the condition.  
And the second thing is that running the play for the second time doesn't result in the ufw rules being deleted. I will make a pull request as soon as I have time to.

**Comment by BrutalBirdie** [comment]
> Yes I know, but the documentation says _yes_ as default, the logic consequence is to use _no_ as the variable value in the play. In the other roles there actually is a _| bool_ behind the condition. So either the documentation has to be changed or to be safe add the _| bool_ to the condition.
> And the second thing is that running the play for the second time doesn't result in the ufw rules being deleted. I will make a pull request as soon as I have time to.
> 
> Edit: I am running on ansible 2.10.11

Ahhhhh yes, yes you are right!
Both the documentation should be updated accordingly and the check to catch this issue.
Since I am working with yamllint and ansible-lint with these rules:
```
rules:
  line-length: false
  document-start: enable
  truthy: enable
```
I never use `yes` or `no` because my lint then complains it should be `true` or `false` so this issue never hit me.
