### ISSUE TITLE
[BUG] - Wrong Kurento default interface used with OpenVZ venet0:0 interface, resulting in ICE 1007 error

### ISSUE THREAD

**Issue by l3d00m** [ebbba-org/ansible-role-bigbluebutton#281]
**Describe the bug**
After #201, installations use `ansible_default_ipv4.interface`. Unfortunately, on my OpenVZ VPS from 1blue it returns `venet0`, which is wrong. It should be `venet0:0`.

For that reason, Kurento isn't listening and users get a ICE 1007 error when listening only or sharing their screen.

**To Reproduce**
1. Deploy this role to an VPS using OpenVZ that has network names like `venet0:0`
2. Interface name inside `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini` is `networkInterfaces=venet0,lo`

**Expected behavior**
Interface names should be `networkInterfaces=venet0:0,lo` (watch the extra :0)

**Ansible version**
Copy-Paste the Output from this command
```bash
# ansible --version
ansible 2.10.9
  config file = None
  configured module search path = ['/home/thomas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/thomas/.local/lib/python3.9/site-packages/ansible
  executable location = /home/thomas/.local/bin/ansible
  python version = 3.9.9 (main, Nov 20 2021, 21:30:06) [GCC 11.1.0]

```

**Your variables for this role - be sure to remove any sensitive information**

```yml
bbb_stun_servers:
    - server: "{{ bbb_hostname }}"
    - server: "stun.l.google.com:19302"
bbb_turn_servers: []
bbb_container_compat: true
bbb_freeswitch_ipv6: false
```
