### ISSUE TITLE
reject outbound traffic to private IP address ranges

### ISSUE THREAD

**Issue by basisbit** [ebbba-org/ansible-role-bigbluebutton#31]
BigBlueButton by default sends data packages to all the IP addresses which the clients send to the server as local IP addresses list so the server can try to send data to there.
Hetzner seems to be annoyed by unroutable traffic. Thus, we should add a reject rule for outbound data to the following address ranges (source is the turn server default config):

- 0.0.0.0-0.255.255.255
- 10.0.0.0-10.255.255.255
- 100.64.0.0-100.127.255.255
- 127.0.0.0-127.255.255.255
- 169.254.0.0-169.254.255.255
- 127.0.0.0-127.255.255.255
- 172.16.0.0-172.31.255.255
- 192.0.0.0-192.0.0.255
- 192.0.2.0-192.0.2.255
- 192.88.99.0-192.88.99.255
- 192.168.0.0-192.168.255.255
- 198.18.0.0-198.19.255.255
- 198.51.100.0-198.51.100.255
- 203.0.113.0-203.0.113.255
- 240.0.0.0-255.255.255.255

Action reject, so that the service doesn't "wait" for a response.

**Comment by t-markmann** [comment]
We've had Hetzner trouble as well. We use scalelite via lazy-deploy and had a faulty IP in docker-compose.yml

See https://github.com/blindsidenetworks/scalelite/issues/381#issuecomment-771749595

**Comment by basisbit** [comment]
*bump*

**Comment by BrutalBirdie** [comment]
This feature should be implemented with issue #24 in mind.

**Comment by BrutalBirdie** [comment]
Hey @basisbit I tested a bit and got out with this, maybe you could check it out and give your opinion.

`defaults/main.yml` adding
```yaml
firewall:
  logging: true
  policy: deny
  # A list of networks that will be reject - https://github.com/ebbba-org/ansible-role-bigbluebutton/issues/31
  # Default reject BOGON https://bgpfilterguide.nlnog.net/guides/bogon_prefixes/#bird
  networks:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 169.0.2.0/16
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
  rules:
    # SSH is allowed by default and limited
    # Allow port 443 - Used by NGINX
    - rule: allow
      port: "443"
      proto: any
    # Allow port 80 - Used by NGINX
    - rule: allow
      port: "80"
      proto: any
    # Allow coturn http port - default used
    - rule: allow
      port: "{{ bbb_coturn_port }}"
      proto: any
    # Allow coturn https (TLS) port - default used
    - rule: allow
      port: "{{ bbb_coturn_port_tls }}"
      proto: any
    # Allow coturn relay ports range - default used
    - rule: allow
      port: "{{ bbb_coturn_min_port }}:{{ bbb_coturn_max_port }}"
      proto: udp
    # Allow BigBlueButton 16384-32768 FreeSWITCH/HTML5 client RTP
    - rule: allow
      port: 16384:32768
      proto: udp
```
and adding a `tasks/ufw.yml`
```yaml
---
- name: Install ufw
  apt:
    pkg: ufw
    state: present

- name: Activate ufw
  # For the setup process we first allow everything by policy,
  # after allowing ssh the default policy will be set to deny.
  community.general.ufw:
    state: enabled
    policy: allow

- name: Set logging
  community.general.ufw:
    logging: true
  when:
    - "'logging' in firewall"
    - "firewall['logging']"

- name: Setup custom rules
  community.general.ufw: "{{ item }}"
  with_items: "{{ firewall['rules'] }}"
  when:
    - "'rules' in firewall"

- name: Reject all out going traffic for networks
  community.general.ufw:
    rule: reject
    direction: out
    src: '{{ item }}'
  with_items: "{{ firewall['networks'] }}"
  when:
    - "'networks' in firewall"

- name: Allow ssh connections
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Connection rate limit for ssh
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Setup default policy
  community.general.ufw:
    policy: deny
  when:
    - "'policy' not in firewall"

- name: Setup custom default policy
  community.general.ufw:
    policy: "{{ firewall['policy'] }}"
  when:
    - "'policy' in firewall"

- name: Reload firewall
  community.general.ufw:
    state: reloaded

```
`172.16.0.0/12` and `127.0.0.1/8` rejected was problematic regarding docker (Greenlight and BBB Exporter)

@genofire you could also take a look regarding issue #24
