### ISSUE TITLE
[BUG] distribution should be focal and was detected as bionic

### ISSUE THREAD

**Issue by casipw** [ebbba-org/ansible-role-bigbluebutton#330]
**Describe the bug**

```
TASK [ebbba.bigbluebutton : check distribution] *****************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {
    "msg": "distribution should be focal and was detected as bionic"
}
```

**To Reproduce**

```
ansible-galaxy install ebbba.bigbluebutton,v2.5.1
ansible-playbook playbook.yml
```

**Expected behavior**

Installation completes.

**Desktop information if needed (please complete the following information):**
 - OS: Ubuntu 18.04

**Ansible version**
Copy-Paste the Output from this command
```bash
# ansible --version
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 
8.4.0]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ansible [core 2.11.2] 
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jun 29 2022, 11:45:57) [GCC 8.4.0]
  jinja version = 2.10
  libyaml = True
```

**Your variables for this role - be sure to remove any sensitive information**

```
- hosts: 127.0.0.1
  connection: local
  roles:
     - { role: ebbba.bigbluebutton, bbb_freeswitch_socket_password: removed, bbb_letsencrypt_email: mail@example.com, bbb_hostname: example.com, bbb_allow_mail_notifications: false, bbb_disable_recordings: yes }
```
